services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=development
    restart: on-failure

  backend:
    build:
      context: ./
      dockerfile: Dockerfile #test
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./manage.py:/app/manage.py
    environment:
      - DEBUG=1
      - PYTHONPATH=/app/backend/bagandgo #test bagandgo ben ekledim
    depends_on:
      - db
    restart: on-failure
    env_file: ./.env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    restart: on-failure

volumes:
  postgres_data:
